export const homeObjOne = {
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
    topLine: '',
    headline: 'Naš zadatak',
    description:
      'Naš osnovni zadatak jeste da donesemo nešto novo, unikatno, zanimljivo i pre svega korisno za studente. Kao konstantni nosioci promena na bolje, svoju ulogu najviše vidimo u poboljšanju kvaliteta studentskog života.',
    buttonLabel: 'Saznaj više',
    imgStart: '',
    img: 'images/home3.png',
    alt: 'Credit Card',
    buttonLink: '/onama'
}; 
export const homeObjTwo = {
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: '',
    headline: 'Naša misija i vizija',
    description:
      'Cilj nam je kreiranje mladih i sposobnih lidera, kako u našoj organizaciji tako i izvan nje. Podstičemo ljude kako na drugačija i kreativna razmišljanja, tako i na profesionalno usavršavanje.',
    buttonLabel: 'Saznaj više',
    imgStart: 'start',
    img: 'images/home2.png',
    alt: 'Vault',
    buttonLink: '/onama'
}; 
  export const homeObjThree = {
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Ekonomski fakultet',
    headline: 'GRUPA ZA SPEKOF',
    description:
      "Grupa za SPEKOF je najveća organizacija u Studentskom parlamentu Ekonomskog fakulteta, čiji se članovi aktivno bore za viši studentski standard od njenog osnivanja, 2012. godine.",
    buttonLabel: 'Saznaj više',
    imgStart: 'start',
    img: 'images/home1.png',
    alt: 'Vault',
    buttonLink: '/onama'
}; 


export const SponsorOne = {
  title : 'Sponzori',
  id : "80ffdfa4-3071-4009-907a-aed9e5f96007",
  img1:'../images/konsek/sponzori (1).png',
  img2:'../images/konsek/sponzori (3).png',
  img3:'../images/konsek/sponzori (4).png',
  img4:'../images/konsek/sponzori (5).png',
  img5:'../images/konsek/sponzori (6).png',
  img6:'../images/konsek/sponzori (7).png',
  img7:'../images/konsek/sponzori (8).png',
  img8:'../images/konsek/sponzori (9).png',
};
export const SponsorTwo = {
  title : 'Sponzori',
  id : "4f29133e-d048-45ff-bc42-30884b6bee05",
  img1:'../images/iw/Bambi.belo.jpg',
  img2:'../images/iw/Carlsberg.belo.jpg',
  img3:'../images/iw/Delhaize.bela.jpg',
  img4:'../images/iw/Erste.belo.jpg',
  img5:'../images/iw/Granice.belo.jpg',
  img6:'../images/iw/Knjaz.belo.jpg',
  img7:'../images/iw/pwc.belo.jpg',
  img8:'../images/iw/Philip.belo.jpg',
};
export const SponsorFour = {
  title : 'Sponzori',
  id : "bbf4e579-c3c9-425b-93b0-e51be4dd0086",
  img1:'../images/ue/7.png',
  img2:'../images/ue/8.png',
  img3:'../images/ue/9.png',
  img4:'../images/ue/10.png',
  img5:'../images/ue/11.png',
  img6:'../images/ue/12.png',
  img7:'../images/ue/13.png',
};
export const SponsorFive = {
  title : 'Sponzori',
  id : "320f0e3c-cb09-4c04-8597-954fb9f9319b",
  img1:'../images/itspace/9.png',
  img2:'../images/itspace/10.png',
  img3:'../images/itspace/11.png',
  img4:'../images/itspace/2.png',
  img5:'../images/itspace/3.png',
  img6:'../images/itspace/7.png',
};

export const PartnerOne = {
  title : 'Partneri',
  id : "80ffdfa4-3071-4009-907a-aed9e5f96007",
  img1:'../images/konsek/sponzori (10).png',
  img2:'../images/konsek/sponzori (12).png',
  img3:'../images/konsek/sponzori (13).png',
  img4:'../images/konsek/sponzori (14).png',
  img5:'../images/konsek/sponzori (15).png',
  img6:'../images/konsek/sponzori (16).png',
  img7:'../images/konsek/sponzori (17).png',
  img8:'../images/konsek/sponzori (18).png',
};
export const PartnerTwo = {
  title : 'Partneri',
  id : "4f29133e-d048-45ff-bc42-30884b6bee05",
  img1:'../images/iw/Bambi.belo.jpg',
  img2:'../images/iw/Carlsberg.belo.jpg',
  img3:'../images/iw/Delhaize.bela.jpg',
  img4:'../images/iw/Erste.belo.jpg',
  img5:'../images/iw/Granice.belo.jpg',
  img6:'../images/iw/Knjaz.belo.jpg',
  img7:'../images/iw/pwc.belo.jpg',
  img8:'../images/iw/Philip.belo.jpg',
};
export const PartnerThree = {
  title : 'Partneri',
  id : "6f40e1a2-4c31-480e-8ef3-07f497473120",
  img1:'../images/vizuelna/2.png',
  img2:'../images/vizuelna/4.png',
  img3:'../images/vizuelna/6.png',
  img4:'../images/vizuelna/8.png',
  img5:'../images/vizuelna/9.png',
  img6:'../images/vizuelna/10.png',
  img7:'../images/vizuelna/13.png',
  img8:'../images/vizuelna/15.png',
  img9:'../images/vizuelna/17.png',
  img10:'../images/vizuelna/19.png',
  img11:'../images/vizuelna/21.png',
};
export const PartnerFour = {
  title : 'Partneri',
  id : "bbf4e579-c3c9-425b-93b0-e51be4dd0086",
  img1:'../images/ue/2.png',
  img2:'../images/ue/3.png',
  img3:'../images/ue/4.png',
  img4:'../images/ue/5.png',
  img5:'../images/ue/11.png',
  img6:'../images/ue/12.png',
  img7:'../images/ue/13.png',
};
export const PartnerFive = {
  title : 'Partneri',
  id : "320f0e3c-cb09-4c04-8597-954fb9f9319b",
  img1:'../images/itspace/2.png',
  img2:'../images/itspace/3.png',
  img3:'../images/itspace/4.png',
  img4:'../images/itspace/5.png',
  img5:'../images/itspace/6.png',
  img6:'../images/itspace/7.png',
};

 export const FriendOne = {
  title : 'Prijatelji',
  img1:'../images/iw/Bambi.belo.jpg',
  img2:'../images/iw/Carlsberg.belo.jpg',
  img3:'../images/iw/Delhaize.bela.jpg',
  img4:'../images/iw/Erste.belo.jpg',
  img5:'../images/iw/Granice.belo.jpg',
  img6:'../images/iw/Knjaz.belo.jpg',
  img7:'../images/iw/pwc.belo.jpg',
  img8:'../images/iw/Philip.belo.jpg',
};



export const ProjectOne = {
  id : "80ffdfa4-3071-4009-907a-aed9e5f96007",
  title : 'KONSEK',
  subtitle: "GRUPA ZA SPEKOF",
  headline : 'Da li želiš da naučiš više o poslovnom svetu i dešavanjima u istom? Stekneš znanje od najuspešnijih ljudi iz oblasti ekonomije, kao i drugih disciplina? Upoznaš svoje kolege i stekneš nova poznanstva? Onda je KONSEK je pravo mesto za tebe!',
  backgroundimage : 'images/konsek/img (57).jpg',
  date : '27-03-2022 : 31-03-2022',
  img1:'images/konsek/img (1).jpg',
  img2:'images/konsek/img (2).jpg',
  img3:'images/konsek/img (3).jpg',
  img4:'images/konsek/img (4).jpg',
  img5:'images/konsek/img (5).jpg',
  img6:'images/konsek/img (6).jpg',
  img7:'images/konsek/img (7).jpg',
  img8:'images/konsek/img (8).jpg',
  img9:'images/konsek/img (9).jpg',
  img10:'images/konsek/img (44).jpg',
  img11:'images/konsek/img (26).jpg',
  img12:'images/konsek/img (55).jpg',
  img13:'images/konsek/img (33).jpg',
  img14:'images/konsek/img (23).jpg',
  text1_title: '',
  text1_subtitle: 'O projektu ',
  text1: 'Kongres studenata ekonomije (KONSEK) u organizaciji Grupe za SPEKOF se već desetu godinu za redom održava na Zlatiboru. Planirano vreme održavanja KONSEK-a je kraj marta, a konferencija traje pet dana. Cilj projekta je okupljanje mladih i ambicioznih studenata, kao i eminentih govornika, predavača i panelista koji će diskutovati o aktuelnim temama. Realizacija ovog projekta doprineće stvaranju stručnih kadrova koji će zajedničkim snagama da formiraju ideje za unapređenje visokog obrazovanja u Srbiji. Studenti treba da budu dobro motivisani da se suoče sa izazovima, stoga želimo da čuju iskustva uspešnih i načine na koje su oni uspeli da prevaziđu neke od poteškoća, kao i njihove doprinose unapređenju visokog obrazovanja. ',
  text2_title: '',
  text2_subtitle: 'Konsek kroz godine',
  text2: 'Tokom svoje desetogodišnje istorije, KONSEK je uspeo da okupi preko 4000 delegata i preko 100 govornika, predavača i panelista. Projekat je već godinama prepoznat i ima podršku najvećih domaćih i svetskih kompanija. Takođe, projekat je bio podržan od strane Ministarstva prosvete, nauke i tehnološkog razvoja, Ministarstva omladine i sporta, Privredne komore Srbije, Narodne banke Srbije kao i Univerziteta u Beogradu. Agendu KONSEK-a su kroz godine obogatile mnoge poznate ličnosti kako iz sveta ekonomije, tako i iz ostalih sfera života. Tihomir Stanić, Bojan Leković, Miodrag Zec, Vanja Grbić su samo neka od velikih imena koja smo imali čast da ugostimo u poslednjih 10 godina.',
  text3_title: '',
  text3_subtitle: 'Spoj edukacije i zabave',
  text3: 'Teme KONSEK-a su uvek bile u skladu sa aktuelnim ekonomskim dešavanjima u regionu i svetu. Kao takve, omogućile su delegatima da sa predavanja, kao i korisnih interaktivnih radionica i panel diskusija, izađu motivisani i spremni za dalji rad na sebi. Pored toga, organizuje se veliki broj različitih aktivnosti i druženja za vreme pauza, a i posle samih predavanja. Interesovanje za KONSEK iz godine u godinu ostaje veliko, a tome najbolje svedoči činjenica da se raspoloživa mesta popune svega 2 minuta nakon otvaranja prijava. Zato je KONSEK godinama najprepoznatljiviji studentski projekat na Ekonomskom fakultetu u Beogradu, ne samo zbog svog kvalitetnog sadržaja, već i zbog odlične zabave i prilika za upoznavanje koje nudi svojim delegatima i predavačima.',
  lightBg1: true,
  lightBg2: true,
  lightBg3: true,
  lightText1: false,
  lightText2: false,
  lightText3: false,
  lightTextDesc1: false,
  lightTextDesc2: false,
  lightTextDesc3: false,
  imgStart1: '',
  imgStart2: 'start',
  imgStart3: '',
};
export const ProjectTwo = {
  id : "4f29133e-d048-45ff-bc42-30884b6bee05",
  title : 'Interviewing Week',
  subtitle: "GRUPA ZA SPEKOF",
  headline : 'Glavni cilj projekta je upoznavanje studenata sa poslovnim svetom. Delegatima se kroz predavanja, radionice i simulacije razgovora za posao pruža prilika za prve korake ka ostvarenju njihovih poslova iz snova.',
  backgroundimage : 'images/iw/img (20).jpg',
  date : '19-02-2022 : 20-02-2022',
  img1:'images/iw/img (1).jpg',
  img2:'images/iw/img (2).jpg',
  img3:'images/iw/img (3).jpg',
  img4:'images/iw/img (4).jpg',
  img5:'images/iw/img (5).jpg',
  img6:'images/iw/img (6).jpg',
  img7:'images/iw/img (7).jpg',
  img8:'images/iw/img (8).jpg',
  img9:'images/iw/img (9).jpg',
  img10:'images/iw/img (22).jpg',
  img11:'images/iw/img (26).jpg',
  img12:'images/iw/img (12).jpg',
  img13:'images/iw/img (13).jpg',
  img14:'images/iw/img (15).jpg',
  text2_title: '',
  text2_subtitle: 'Tok projekta',
  text2: 'Prvog dana, akcenat stavljamo na interaktivna predavanja, radionice, treninge ili panel diskusije koje održavamo u saradnji sa predstavnicima različitih kompanija.  Kroz interaktivna predavanja  prvog dana, delegati se susreću sa idejom projekta i imaju priliku da se pripreme za dalje izazove koji ih očekuju u narednom periodu. Na radionicama i treninzima, radimo na njihovom usavršavanju i što boljem prezentovanju njihovih potencijala, iskustava i znanja.Nakon toga, mogu da čuju nešto više o kompanijama i njihovom radu na panel diskusiji. Drugog dana, delegati su ti koji treba da se pokažu u najboljem svetlu. Predstavljaju svoja rešenja studije slučaja i imaju mogućnost intervjua sa jednom od kompanija, koju su oni izabrali prilikom prijava za učestvovanje na samom projektu.',
  text1_title: '',
  text1_subtitle: 'O projektu',
  text1: 'Interviewing week je projekat edukativnog i praktičnog karaktera, koji za cilj ima da unapredi komunikaciju naših studenata sa poslodavcima iz raznih sfera poslovanja. Delegatima se pruža prilika da kroz CV radionice, predavanja, simulacije razgovora za posao i izrade studije slučaja unaprede svoje prezentacione veštine i poboljšaju poslovnu komunikaciju . Takođe, delegati imaju priliku da po prvi put stupe u dodir sa poslovnim svetom i susretnu se sa realnim problemima naših kompanija.Projekat je prvi put realizovan 2015. i primarno je namenjen studentima treće i četvrte godine. Održava se jednom godišnje, poslednjeg vikedna februara na Ekonomskom fakultetu, Univerziteta u Beogradu. ',
  text3_title: '',
  text3_subtitle: 'Koji savet bi dali studentima koji žele da se prijave na projekat? ',
  text3: 'Drage kolege, obavezno se prijavite na projekat jer možete dosta praktičnih stvari da naučite, ostvarite kontakte i oslobodite se treme. Šta god radite u životu, najbitnija stvar je vežba i da vam neko ukaže na greške koje pravite. Ne shvatajte to kao kritiku, već da je ceo tim organizatora i kompanija tu da vam pomogne prilikom ostvarenja vaših ciljeva. Srećno!',
  lightBg1: true,
  lightBg2: true,
  lightBg3: true,
  lightText1: false,
  lightText2: false,
  lightText3: false,
  lightTextDesc1: false,
  lightTextDesc2: false,
  lightTextDesc3: false,
  imgStart1: '',
  imgStart2: 'start',
  imgStart3: '',
};
export const ProjectThree = {
  id : "6f40e1a2-4c31-480e-8ef3-07f497473120",
  title : 'Vizuelna ekonomija',
  subtitle: "Grupa za SPEKOF",
  headline : 'Vizuelna ekonomija je projekat koji se ove godine po peti put održao na Ekonomskom fakultetu u Beogradu. Cilj projekta je da kroz tri nedelje održavanja predavanja i radionica pruži delegatima adekvatno znanje iz oblasti marketinga. Kroz dva dana nedeljno okupili smo uspešne inspirativne ljude iz marketing industrije koji su, prenoseći svoje iskustvo i znanje, uveli studente Ekonomskog fakulteta u realan svet marketinga kakav nemaju priliku da upoznaju na formalnim studijama.',
  backgroundimage : 'images/ue/image (7).jpg',
  date : '20-11-2021 : 05-12-2021',
  img1:'images/vizuelna/image (1).jpg',
  img2:'images/vizuelna/image (2).jpg',
  img3:'images/vizuelna/image (3).jpg',
  img4:'images/vizuelna/image (4).jpg',
  img5:'images/vizuelna/image (5).jpg',
  img6:'images/vizuelna/image (6).jpg',
  img7:'images/vizuelna/image (7).jpg',
  img8:'images/vizuelna/image (8).jpg',
  img9:'images/vizuelna/image (9).jpg',
  img10:'images/vizuelna/image (22).jpg',
  img11:'images/vizuelna/image (26).jpg',
  img12:'images/vizuelna/image (12).jpg',
  img13:'images/vizuelna/image (13).jpg',
  img14:'images/vizuelna/image (15).jpg',
  text1_title: '',
  text1_subtitle: 'Jesenja škola marketinga',
  text1: 'Petu godinu za redom jesenja škola marketinga, poznatija kao Vizuelna ekonomija-VIZEK okuplja mnogobrojne stručnjake u sferi marketinga kako bi delegatima na sveobuhvatan  i  zanimljiv način uspela da predstavi marketing kao nauku! Projekat traje 3 nedelje, svake nedelje, obično 2 dana u nedelji  delegati se druže sa našim predavačima i imaju priliku da nauče nešto novo! Svaka nedelja sa sobom nosi nove čari marketinga!',
  text2_title: '',
  text2_subtitle: 'VIZEK 2020. godine',
  text2: 'Vizuelna ekonomija 2020. godine održala se onlajn, putem Zoom aplikacije, a tema joj je bila "Marketing kroz vreme". Delegati su imali prilike da čuju o tradicionalnom, ali i modernom marketingu od poznatih srpskih marketara i stručnjaka poput Petra Vasića, dr Dragana Veselinovića, Daše Danilović itd. Pored toga, imali su priliku da rešavaju studije slučaja bazirane na realnim situacijama kompanija učesnica, a ove godine su to bili, između ostalog, PepsiCo i Zlato u tegli.',
  text3_title: '',
  text3_subtitle: 'Više o projektu',
  text3: 'Delegati su imali priliku da rešavaju realne probleme kompanija učesnika projekta kroz različite radionice i takmičenja, da posete kreativne agencije, agencije za istraživanje tržišta i produkcijske kuće.',
  lightBg1: true,
  lightBg2: true,
  lightBg3: true,
  lightText1: false,
  lightText2: false,
  lightText3: false,
  lightTextDesc1: false,
  lightTextDesc2: false,
  lightTextDesc3: false,
  imgStart1: '',
  imgStart2: 'start',
  imgStart3: '',
};
export const ProjectFour= {
  id : "bbf4e579-c3c9-425b-93b0-e51be4dd0086",
  title : 'Upoznaj ekof',
  subtitle: "GRUPA ZA SPEKOF",
  headline : 'Projekat "Upoznaj EKOF" ima za cilj da studente koji su tek upisali fakultet informiše o svim bitnim stavkama vezanim za fakultet, od informacija vezanih za same predmete do tehničkih stvari!',
  backgroundimage : 'images/ue/image (7).jpg',
  date : '22-10-2021 : 24-10-2021',
  img1:'images/ue/image (1).jpg',
  img2:'images/ue/image (2).jpg',
  img3:'images/ue/image (3).jpg',
  img4:'images/ue/image (4).jpg',
  img5:'images/ue/image (5).jpg',
  img6:'images/ue/image (6).jpg',
  img7:'images/ue/image (7).jpg',
  img8:'images/ue/image (8).jpg',
  img9:'images/ue/image (9).jpg',
  img10:'images/ue/image (20).jpg',
  img11:'images/ue/image (11).jpg',
  img12:'images/ue/image (12).jpg',
  img13:'images/ue/image (13).jpg',
  img14:'images/ue/image (15).jpg',
  text1_title: '',
  text1_subtitle: 'Kratka istorija projekta',
  text1: 'Projekat je prvi put realizovan 2012. godine, do tada pa sve do danas na konferenciju se prijavilo preko 1200 delegata, a o "Upoznaj EKOF"- u imali su samo reči hvale.',
  text2_title: '',
  text2_subtitle: 'Kako je projekat zamišljen',
  text2: 'Konferencija se tradicionalno održava u studentskom odmaralištu "Radojka Lakić" . Studenti imaju pripremljen program za 3 dana i 2 noći kojim se trudimo da  dočaramo i što realnije prikažemo fakultet, ali i da obuhvatimo i što više tema koje interesuju naše delegate. Kroz "Upoznaj EKOF" prošla su mnoga velika imena, kao i firme koji su nam pomogli da sve učinimo još boljim!',
  text3_title: '',
  text3_subtitle: 'Projekat 2021. godine',
  text3: 'Po prvi put konferencija je održana na Zlatiboru u studentskom odmaralištu "Ratko Mitrović". Konferenciju je otvorio profesor Slobodan Aćimović, a ostatak prvog dana upotpunila su predavanja posvećena upoznavanju prve godine gde su delegati imali priliku da razgovaraju sa starijim kolegama. Drugi dan bio je posvećen upoznavanju vannastavnih aktivnosti koje fakultet nudi. Prethodnih godina "Upoznaj EKOF" podržali su  PepsiCo, Knjaz Miloš, Guarana, Rubin kao i mnogi drugi!',
  lightBg1: true,
  lightBg2: true,
  lightBg3: true,
  lightText1: false,
  lightText2: false,
  lightText3: false,
  lightTextDesc1: false,
  lightTextDesc2: false,
  lightTextDesc3: false,
  imgStart1: '',
  imgStart2: 'start',
  imgStart3: '',
};
export const ProjectFive= {
  id : "320f0e3c-cb09-4c04-8597-954fb9f9319b",
  title : 'IT SPACE',
  subtitle: "GRUPA ZA SPEKOF",
  headline : 'IT Space je nastao kao ideja da se spoje dve nauke, ekonomija i informatika. Projekat traje dva dana i trudi se da pokrije što više tema vezanih za novosti. ',
  backgroundimage : 'images/ue/image (7).jpg',
  date : '11-12-2021 : 12-12-2021',
  img1:'images/itspace/image (1).jpg',
  img2:'images/itspace/image (2).jpg',
  img3:'images/itspace/image (3).jpg',
  img4:'images/itspace/image (4).jpg',
  img5:'images/itspace/image (5).jpg',
  img6:'images/itspace/image (6).jpg',
  img7:'images/itspace/image (7).jpg',
  img8:'images/itspace/image (8).jpg',
  img9:'images/itspace/image (9).jpg',
  img10:'images/itspace/image (20).jpg',
  img11:'images/itspace/image (11).jpg',
  img12:'images/itspace/image (12).jpg',
  img13:'images/itspace/image (13).jpg',
  img14:'images/itspace/image (15).jpg',
  text1_title: '',
  text1_subtitle: 'Beyond virtual',
  text1: 'Beyond Virtual je tema konferencije 2021. godine. U dva dana obradili smo najaktuelnije teme i  inovacije.  Neki od naših predavača  bili su zaposleni iz raznih IT kompanija i ugledni ljudi iz IT sveta.',
  text2_title: '',
  text2_subtitle: 'Više o projektu',
  text2: 'Seminar o informacionim tehnologijama organizuje se sa ciljem okupljanja studenta ekonomije, eminentnih predavača i panelista iz akademskog i poslovnog života, koji će studente bolje upoznati sa potencijalima sektora informacionih tehnologija u Srbiji. Seminar traje dva dana, a održava se na Ekonomskom fakultetu, početkom decembra.Projekat se organizuje kako bi se studentima pružila prilika da se bolje informišu o potencijalima ovog sektora, obzirom da se informacione tehnologije ne izučavaju u velikoj meri na Ekonomskom fakultetu.',
  text3_title: '',
  text3_subtitle: 'Misija',
  text3: 'Misija projekta je podsticanje međugeneracijske komunikacije, kao i zajednička saradnja na polju informacionih tehnologija i razvoja internet biznisa. Vizija projekta je pružanje studentima što boljih znanje iz ovih oblasti, kako bi se brže i lakše pridružili poslovnom svetu.',
  lightBg1: true,
  lightBg2: true,
  lightBg3: true,
  lightText1: false,
  lightText2: false,
  lightText3: false,
  lightTextDesc1: false,
  lightTextDesc2: false,
  lightTextDesc3: false,
  imgStart1: '',
  imgStart2: 'start',
  imgStart3: '',
};

export const NewsOne = {
  id : "882e329a-3ad2-46eb-af8d-5a7ddeef65d5",
  title : 'Humanitarno Stand-up ',
  headline : 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry',
  backgroundimage : 'images/perisic.png',
  subtitle: "Godinama unazad, Grupa za Spekof učestvuje i u organizovanju humanitarnih akcija. Nastavili smo tradiciju i ove godine, priredivši humanitarno stand up veče koje se održalo 16. decembra 2021. godine i na kojem je nastupio Aleksandar Perišić. Iako ovo nije bio njegov prvi nastup u zgradi Ekonomskog fakulteta, izdvojili bismo ga kao najupečatljivijim, jer smo uspeli da prikupimo čak 110100 dinara! Ukupan iznos je doniran dečijem odeljenju Instituta za Radiologiju i Onkologiju u Tiršovoj bolnici. Dodatnu radost smo osetili kad nam je sam gospođa iz ovog udruženja rekla da nikada za jedno veče ovoliko novca nije bilo sakupljeno! Uz sjajnu atmosferu koju nam je priredio i osmehe koje nam je izmamio Aleksandar, veče je bilo maksimalno ulepšano. Pomoći nekome kome je najpotrebnije je neprocenljiv osećaj.", 
};


export const GroupOne = {
  title : 'Tim koordinatora',
  idProject : '80ffdfa4-3071-4009-907a-aed9e5f96007',
  LukaTumbas : 'images/konsek/tumbas.jpeg',
  MilosGrković : 'images/konsek/grkovic.jpeg',
  person3 : 'images/img-3.jpg',
  person4 : 'images/img-3.jpg',
  person5 : 'images/img-3.jpg',
  person6 : 'images/img-3.jpg',
  html1 : 'https://rs.linkedin.com/in/luka-tumbas-5ab8a21b5',
  html2 : 'https://rs.linkedin.com/in/milo%C5%A1-grkovi%C4%87-3741821a2',
  html3 : 'http://www.facebook.com',
  html4 : 'http://www.facebook.com',
  html5 : 'http://www.facebook.com',
  html6 : 'http://www.facebook.com',
  email1 : 'lukatumbas25@gmail.com',
  email2 : 'grmilos99@gmail.com',
  email3 : 'pajapatak@gmail.com',
  email4 : 'pajapatak@gmail.com',
  email5 : 'pajapatak@gmail.com',  
  email6 : 'pajapatak@gmail.com'
};
export const GroupTwo = {
  title : 'Tim necega2',
  idProject : "4f29133e-d048-45ff-bc42-30884b6bee05",
  AndreaJovanović : '../images/iw/andrea.jpeg',
  BoškoPetrović : '../images/iw/bosko.jpeg',
  person3 : 'images/img-3.jpg',
  person4 : 'images/img-3.jpg',
  person5 : 'images/img-3.jpg',
  person6 : 'images/img-3.jpg',
  html1 : 'http://www.facebook.com',
  html2 : 'https://www.linkedin.com/in/boško-petrović-3692771aa',
  html3 : 'http://www.facebook.com',
  html4 : 'http://www.facebook.com',
  html5 : 'http://www.facebook.com',
  html6 : 'http://www.facebook.com',
  email1 : 'andrea00jovanovic@gmail.com',
  email2 : 'bosko12petrovic@hotmail.com',
  email3 : 'pajapatak@gmail.com',
  email4 : 'pajapatak@gmail.com',
  email5 : 'pajapatak@gmail.com',  
  email6 : 'pajapatak@gmail.com'
};
export const GroupThree = {
  title : 'Tim necega3',
  idProject : "6f40e1a2-4c31-480e-8ef3-07f497473120",
  MiroslavVuletić : 'images/vizuelna/miroslav.jpeg',
  MijaBukorović : 'images/vizuelna/mija.jpeg',
  person3 : 'images/img-3.jpg',
  person4 : 'images/img-3.jpg',
  person5 : 'images/img-3.jpg',
  person6 : 'images/img-3.jpg',
  html1 : 'http://www.linkedin.com',
  html2 : 'http://www.linkedin.com',
  html3 : 'http://www.facebook.com',
  html4 : 'http://www.facebook.com',
  html5 : 'http://www.facebook.com',
  html6 : 'http://www.facebook.com',
  email1 : 'm.vuletic00@gmail.com',
  email2 : 'mija.n.bukorovic@gmail.com',
  email3 : 'pajapatak@gmail.com',
  email4 : 'pajapatak@gmail.com',
  email5 : 'pajapatak@gmail.com',  
  email6 : 'pajapatak@gmail.com'
};
export const GroupFour = {
  title : 'Tim koordinatora',
  idProject : "bbf4e579-c3c9-425b-93b0-e51be4dd0086",
  JelenaMilojević : 'images/ue/jelena.jpeg',
  AndreaJovanović : '../images/iw/andrea.jpeg',
  person3 : 'images/img-3.jpg',
  person4 : 'images/img-3.jpg',
  person5 : 'images/img-3.jpg',
  person6 : 'images/img-3.jpg',
  html1 : 'http://www.facebook.com',
  html2 : 'https://www.linkedin.com/in/andrea-jovanovic-749995203',
  html3 : 'http://www.facebook.com',
  html4 : 'http://www.facebook.com',
  html5 : 'http://www.facebook.com',
  html6 : 'http://www.facebook.com',
  email1 : 'milojevicjelena51@gmail.com',
  email2 : 'andrea00jovanovic@gmail.com',
  email3 : 'pajapatak@gmail.com',
  email4 : 'pajapatak@gmail.com',
  email5 : 'pajapatak@gmail.com',  
  email6 : 'pajapatak@gmail.com'
};
export const GroupFive = {
  title : 'Tim koordinatora',
  idProject : "320f0e3c-cb09-4c04-8597-954fb9f9319b",
  JelenaMilojević : 'images/ue/jelena.jpeg',
  KatarinaNikolić : '../images/ue/kaca.jpeg',
  person3 : 'images/img-3.jpg',
  person4 : 'images/img-3.jpg',
  person5 : 'images/img-3.jpg',
  person6 : 'images/img-3.jpg',
  html1 : 'http://www.linkedin.com',
  html2 : 'https://www.linkedin.com/mwlite/in/katarina-nikoli%C4%87-41a5a2205',
  html3 : 'http://www.facebook.com',
  html4 : 'http://www.facebook.com',
  html5 : 'http://www.facebook.com',
  html6 : 'http://www.facebook.com',
  email1 : 'milojevicjelena51@gmail.com',
  email2 : 'nikolickatarina1505@gmail.com',
  email3 : 'pajapatak@gmail.com',
  email4 : 'pajapatak@gmail.com',
  email5 : 'pajapatak@gmail.com',  
  email6 : 'pajapatak@gmail.com'
};